version: "3.8"
services:
  privateglue:
    image: ghcr.io/marcmylemans/privateglue:latest
    ports:
      - "5000:5000"
    volumes:
      - ./notes:/app/notes
      - ./data:/app/data
      - ./backups:/app/backups
      - secretkey:/app/secret  # use a named volume
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
volumes:
  secretkey:
