FROM python:3.11-slim

WORKDIR /app

COPY backend/ /app/backend
#COPY notes/ /app/notes
COPY requirements.txt /app

ENV PYTHONPATH="${PYTHONPATH}:/app"

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "backend/app.py"]
